/*
 * Copyright (C) 2007 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.ide.common.resources;

import com.android.ide.common.rendering.api.ResourceValue;
import com.android.ide.common.resources.configuration.Configurable;
import com.android.ide.common.resources.configuration.FolderConfiguration;
import com.android.io.IAbstractFile;
import com.android.resources.ResourceType;

import java.util.Collection;

/**
 * Represents a Resource file (a file under $Project/res/)
 */
public abstract class ResourceFile implements Configurable {

    /**
     * The {@link IAbstractFile} object for this resource file.
     */
    private final IAbstractFile mFile;
    /**
     * The {@link ResourceFolder} containing this resource file.
     */
    private final ResourceFolder mFolder;

    /**
     * @param file   the {@link IAbstractFile} object
     * @param folder the {@link ResourceFolder} containing this resource file
     */
    protected ResourceFile(IAbstractFile file, ResourceFolder folder) {
        mFile = file;
        mFolder = folder;
    }

    /**
     * @param context the {@link ScanningContext} to use
     */
    protected abstract void load(ScanningContext context);

    /**
     * @param context the {@link ScanningContext} to use
     */
    protected abstract void update(ScanningContext context);

    /**
     * @param context the {@link ScanningContext} to use
     */
    protected abstract void dispose(ScanningContext context);

    /**
     * @return the {@link FolderConfiguration} associated with the ResourceFile
     */
    @Override
    public FolderConfiguration getConfiguration() {
        return mFolder.getConfiguration();
    }

    /**
     * Returns the IFile associated with the ResourceFile.
     *
     * @return the IFile associated with the ResourceFile.
     */
    public final IAbstractFile getFile() {
        return mFile;
    }

    /**
     * Returns the parent folder as a {@link ResourceFolder}.
     *
     * @return the parent folder as a {@link ResourceFolder}.
     */
    public final ResourceFolder getFolder() {
        return mFolder;
    }

    /**
     * @return the {@link ResourceRepository} associated with this resource file.
     */
    public final ResourceRepository getRepository() {
        return mFolder.getRepository();
    }

    /**
     * Returns whether the resource is a framework resource.
     *
     * @return true if the resource is a framework resource
     */
    public final boolean isFramework() {
        return mFolder.getRepository().isFrameworkRepository();
    }

    /**
     * Returns the list of {@link ResourceType} generated by the file. This is never null.
     *
     * @return a list of {@link ResourceType} generated by the file.
     */
    public abstract Collection<ResourceType> getResourceTypes();

    /**
     * Returns whether the file generated a resource of a specific type.
     *
     * @param type The {@link ResourceType}
     * @return true if the file generated a resource of the given type
     */
    public abstract boolean hasResources(ResourceType type);

    /**
     * Returns the value of a resource generated by this file by {@link ResourceType} and name.
     * <p>If no resource match, <code>null</code> is returned.
     *
     * @param type the type of the resource.
     * @param name the name of the resource.
     * @return the {@link ResourceValue} or <code>null</code> if not found
     */
    public abstract ResourceValue getValue(ResourceType type, String name);

    /**
     * @return a string representation of this object
     */
    @Override
    public String toString() {
        return mFile.toString();
    }
}

